default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe-exchange_development
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: recipe-exchange_test
  username: <%= ENV['TEST_DB_USER'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>

stage:
  <<: *base
  host: <%= ENV['STAGE_HOST'] %>
  database: <%= ENV['STAGE_DB_NAME'] %>
  username: <%= ENV['STAGE_USER'] %>
  password: <%= ENV['STAGE_PASSWORD'] %>

production:
  <<: *base
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
